[package]
name = "cbfs"
version = "0.1.0"
edition = "2024"

[dependencies]
cbfs-lib = { path = "../cbfs-lib", version = "*" }
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
simple_logger = "5.1"

[target.'cfg(target_os = "linux")'.dependencies]
fuser = "0.16"
