[package]
name = "jib"
version = "0.1.0"
edition = "2024"
authors = ["Ian O'Rourke <cessna.ian@gmail.com>"]

[dependencies]
chrono = { version = "0.4", optional = true }

[features]
default = ["rtcdev"]
std = []
rtcdev = ["std", "dep:chrono"]
