[workspace]

members = [
    "cbuoy",
    "cbc",
    "cbfs/compat",
    "cbfs-lib",
    "jib-asm",
    "jib",
    "visual-jib",
]
default-members = ["visual-jib"]
resolver = "2"

[profile.release]
lto = true
strip = true
